// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Rox9yPjhHbrmKLJJZFsBQ27rA3YehUo',
    appId: '1:234115425088:web:059dd4e4d8ef71c8c910a5',
    messagingSenderId: '234115425088',
    projectId: 'goal-tracker-app-4ce5b',
    authDomain: 'goal-tracker-app-4ce5b.firebaseapp.com',
    storageBucket: 'goal-tracker-app-4ce5b.firebasestorage.app',
    measurementId: 'G-9N8C3G8EZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrzYXmAC61GWTnYsrvAP5singdBf3Ijc',
    appId: '1:234115425088:android:067b4ee4249f4a69c910a5',
    messagingSenderId: '234115425088',
    projectId: 'goal-tracker-app-4ce5b',
    storageBucket: 'goal-tracker-app-4ce5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_x81ckh66oMMc9ezpBTqfETlhZ4G7ZU',
    appId: '1:234115425088:ios:21f438bdb2166155c910a5',
    messagingSenderId: '234115425088',
    projectId: 'goal-tracker-app-4ce5b',
    storageBucket: 'goal-tracker-app-4ce5b.firebasestorage.app',
    iosBundleId: 'com.example.goalTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_x81ckh66oMMc9ezpBTqfETlhZ4G7ZU',
    appId: '1:234115425088:ios:21f438bdb2166155c910a5',
    messagingSenderId: '234115425088',
    projectId: 'goal-tracker-app-4ce5b',
    storageBucket: 'goal-tracker-app-4ce5b.firebasestorage.app',
    iosBundleId: 'com.example.goalTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Rox9yPjhHbrmKLJJZFsBQ27rA3YehUo',
    appId: '1:234115425088:web:ac78f1c71fae1da4c910a5',
    messagingSenderId: '234115425088',
    projectId: 'goal-tracker-app-4ce5b',
    authDomain: 'goal-tracker-app-4ce5b.firebaseapp.com',
    storageBucket: 'goal-tracker-app-4ce5b.firebasestorage.app',
    measurementId: 'G-5VE60SGVME',
  );
}
